obstacle_range: .8
raytrace_range: 3.5

#footprint: [[-0.13, -0.13], [-0.13, 0.13], [0.13, 0.13], [0.13, -0.13]]
robot_radius: 0.25

inflation_radius: .8
cost_scaling_factor: 3.0

map_type: costmap
observation_sources: scan
scan: {sensor_frame: base_scan, data_type: LaserScan, topic: hello_robot/scan, marking: true, clearing: true}