#obstacle_range: 3
#raytrace_range: 3.5

#footprint: [[-0.13, -0.13], [-0.13, 0.13], [0.13, 0.13], [0.13, -0.13]]
#robot_radius: 0.25

#inflation_radius: .8
#cost_scaling_factor: 3.0

#map_type: costmap
#observation_sources: scan
#scan: {sensor_frame: base_scan, data_type: LaserScan, topic: hello_robot/scan, marking: true, clearing: true}

robot_base_frame: base_footprint
robot_radius: 0.15
transform_tolerance: 0.4
update_frequency: 5.0
publish_frequency: 1.0
obstacle_range: 3.0
#mark_threshold: 1
publish_voxel_map: true
navigation_map:
  map_topic: /map
obstacles:
  observation_sources: scan
  scan:
    topic: hello_robot/scan
    data_type: LaserScan
    clearing: false
    marking: true
    inf_is_valid: false
    min_obstacle_height: 0.13
    max_obstacle_height: 0.25
virtual_walls_map:
  map_topic: /virtual_walls/map
  use_maximum: true