<?xml version="1.0"?>
<robot name="hello_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="package_name" value="hello_robot" />
  <xacro:property name="robot_name" value="hello_robot" />

  <xacro:include filename="$(find ${package_name})/urdf/hello_robot.gazebo.xacro" />
  <xacro:include filename="$(find ${package_name})/urdf/include/common_macros.urdf.xacro" />
  <xacro:include filename="$(find ${package_name})/urdf/include/common_sensors.xacro" />

  <xacro:property name="sensor_yaml" value="$(find ${package_name})/config/sensors.yaml" />
  <xacro:property name="sensor_prop" value="${load_yaml(sensor_yaml)}"/>


  <xacro:property name="baselen" value="0.24" />
  <xacro:property name="basewidth" value="0.15" />
  <xacro:property name="basethick" value="0.003" />
  <xacro:property name="wheeldiam" value="0.056" />
  <xacro:property name="wheelwidth" value="0.037" />
  <xacro:property name="wheel_x_pos" value="0.10" />
  <xacro:property name="wheel_y_pos" value="${basewidth/2+.035}" />
  <xacro:property name="wheel_z_pos" value="${-((basethick/2)+(wheeldiam/2)+.01)}" />
  <xacro:property name="pi" value="3.1415926535" />

  <link name="base_footprint" />
  <!-- Joint to connect base_footprint with base_link -->
  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link" />
    <origin xyz="0 0 ${(wheeldiam/2)+(-wheel_z_pos)}" rpy="0 0 0" />
  </joint>

  <link name="base_link">
    <visual>
      <geometry>
        <box size="${baselen} ${basewidth} ${basethick}" />
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <geometry>
        <box size="${baselen} ${basewidth} ${basethick}" />
      </geometry>
    </collision>
    <xacro:base_inertia m="1.065" 
    x="${baselen}" y="${basewidth}" z="${basethick}" 
    o_xyz="0.0 0.0 0.0" o_rpy="0.0 0.0 0.0"
    />
  </link>

  <xacro:wheel prefix="left" suffix="front" m="0.087" r="${wheeldiam/2}" l="${wheelwidth}" x_pos="${wheel_x_pos}" y_pos="${wheel_y_pos}" z_pos="${wheel_z_pos}"/>
  <xacro:wheel prefix="left" suffix="back" m="0.087" r="${wheeldiam/2}" l="${wheelwidth}" x_pos="${-wheel_x_pos}" y_pos="${wheel_y_pos}" z_pos="${wheel_z_pos}"/>
  <xacro:wheel prefix="right" suffix="front" m="0.087" r="${wheeldiam/2}" l="${wheelwidth}" x_pos="${wheel_x_pos}" y_pos="${-wheel_y_pos}" z_pos="${wheel_z_pos}"/>
  <xacro:wheel prefix="right" suffix="back" m="0.087" r="${wheeldiam/2}" l="${wheelwidth}" x_pos="${-wheel_x_pos}" y_pos="${-wheel_y_pos}" z_pos="${wheel_z_pos}"/>

  <!-- Sensors -->
  <xacro:gpu_laser prefix="rplidar" parent_link="base_link"
                   sensor_prop="${sensor_prop}"> 
  </xacro:gpu_laser>

</robot>