<?xml version="1.0"?>
<robot name="hello_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="baselen" value="0.023" />
  <xacro:property name="basewidth" value="0.026" />
  <xacro:property name="basethick" value="0.005" />
  <xacro:property name="wheeldiam" value="0.0065" />
  <xacro:property name="wheelwidth" value="0.0065" />
  <xacro:property name="pi" value="3.1415" />
  <xacro:property name="mass" value="1" />

  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>

  <xacro:macro name="default_inertial" params="mass">
    <inertial>
      <mass value="${mass}" />
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
    </inertial>
  </xacro:macro>

  <link name="base_link">
    <visual>
      <geometry>
        <box size="${baselen} ${basewidth} ${basethick}" />
      </geometry>
      <material name="white"/>
    </visual>
  </link>

  <xacro:macro name="wheel" params="prefix suffix reflect">

    <link name="${prefix}_${suffix}_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
        <geometry>
          <cylinder radius="${wheeldiam/2}" length="${wheelwidth}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
        <geometry>
          <cylinder radius="${wheeldiam/2}" length="${wheelwidth}"/>
        </geometry>
      </collision>
      <xacro:default_inertial mass="1"/>
    </link>
    <joint name="${prefix}_${suffix}_wheel_joint" type="continuous">
      <axis xyz="0 1 0" rpy="0 0 0" />
      <parent link="base_link"/>
      <child link="${prefix}_${suffix}_wheel"/>
      <origin xyz="${baselen*reflect/3} ${.015} -${wheeldiam/2}" rpy="0 0 0"/>
    </joint>

  </xacro:macro>

  <xacro:wheel prefix="left" suffix="front" reflect="1"/>
  <xacro:wheel prefix="left" suffix="rear" reflect="-1"/>

</robot>