gpu_laser:
  mass: 0.1          # Motor mass in Kg
  radius: 0.015     # Wheel radius in m
  length: 0.01      # Wheel length in m, considering is as a cylinder
  mesh: ''  # Name of the mesh files. Leave it empty ('') to have a red wheel
  #mesh: ''
  dx: 0.0
  dy: 0.0
  dz: 0.0
  angular_range:
    min: -1.1415
    max: 1.1415